name: Build Static Next.js

on:
  workflow_run:
    workflows: ["Apply Resume Updates"]
    types:
      - completed
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Lint
        run: npm run lint || echo "Linting issues found"
        
      - name: Type check
        run: npm run typecheck || echo "Type issues found"
        
      - name: Run tests
        run: npm test || echo "Tests failed"

  generate-ats:
    needs: lint-and-test
    uses: ./.github/workflows/generate-ats-cv.yml

  build:
    needs: generate-ats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'  
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin master 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Set repository name for basePath
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "NEXT_PUBLIC_BASE_PATH=/$REPO_NAME" >> $GITHUB_ENV
          echo "Using base path: /$REPO_NAME"

      - name: Build static site
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4