name: Generate ATS CV

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      json_changes_detected: ${{ steps.check_json_changes.outputs.json_changes_detected }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in JSON data files
        id: check_json_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "src/data/.*\.json"; then
            echo "JSON data files have changed"
            echo "json_changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in JSON data files"
            echo "json_changes_detected=false" >> $GITHUB_OUTPUT
          fi

  generate-ats:
    needs: check-changes
    if: needs.check-changes.outputs.json_changes_detected == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm init -y
          npm install markdown-it puppeteer

      - name: Generate ATS Markdown
        run: npx tsx scripts/generate-ats-md.ts

      - name: Check for changes in MD file
        id: check_md_changes
        run: |
          if [ -f public/ats/cv-ats.md ] && git diff --quiet public/ats/cv-ats.md; then
            echo "No changes detected in cv-ats.md"
            echo "md_changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in cv-ats.md or file doesn't exist"
            echo "md_changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate ATS PDF

        run: npx tsx scripts/generate-ats-pdf.ts

      - name: Upload ATS CV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ats-cv
          path: |
            public/ats/cv-ats.md
            public/ats/cv-ats.pdf
        if: steps.check_md_changes.outputs.md_changes_detected == 'true' || github.event_name == 'workflow_dispatch'

      - name: Commit ATS CV
        if: steps.check_md_changes.outputs.md_changes_detected == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add public/ats/cv-ats.md public/ats/cv-ats.pdf
          git commit -m "Update ATS CV"
          git push
