name: Yearly Date Update

on:
  schedule:
    # Run at 00:05 on January 1
    - cron: '5 0 1 1 *'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Static workflow
        uses: ./.github/workflows/build-static.yml